version: "2"
services:
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    image: matthewlimfaylay/usermgmt
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - mongo
